"use client"
import Link from "next/link"
import {useEffect,useState} from "react"
type Fact={title:string;text:string;source:string}; type State={view:string;facts:string[];flags:string[]}
const F:Record<string,Fact>={
incident:{title:"The child in the by-street",text:"Enfield saw Hyde collide with a young girl and then calmly trample over her body, leaving her screaming in the street.",source:"Richard Enfield"},
settlement:{title:"The settlement",text:"Enfield, the child's family and a doctor detained Hyde until he agreed to pay one hundred pounds.",source:"Richard Enfield"},
door:{title:"The neglected door",text:"Hyde possessed a key to the neglected door and used it to fetch the settlement money.",source:"Richard Enfield"},
cheque:{title:"The cheque",text:"Most of the settlement was paid by a genuine cheque bearing the name of a well-known and respectable gentleman. Enfield will not disclose that name.",source:"Richard Enfield"},
name:{title:"Edward Hyde",text:"The man who trampled the child gave his name as Edward Hyde.",source:"Richard Enfield"},
impression:{title:"Enfield's impression of Hyde",text:"Enfield remembers Hyde clearly yet cannot identify any particular deformity; only an immediate and powerful sense that something about him is detestable.",source:"Richard Enfield"},
key:{title:"Hyde still has the key",text:"Enfield has seen Hyde use the same key within the last week.",source:"Richard Enfield"},
place:{title:"Enfield's observations of the building",text:"The door is rarely used. The upper windows are shut but clean, and a chimney commonly smokes. The crowded buildings make it difficult to tell where one property ends and another begins.",source:"Richard Enfield"}}
const start:State={view:"opening",facts:[],flags:[]}; const add=(xs:string[],...ys:string[])=>[...new Set([...xs,...ys])]
function Choice({children,onClick}:{children:React.ReactNode,onClick:()=>void}){return <button className="jh-choice" onClick={onClick}>{children}</button>}
export default function Page(){
 const [s,setS]=useState<State>(start); const [paper,setPaper]=useState<string|null>(null)
 useEffect(()=>{const x=localStorage.getItem("open-shelf-jh-s1");if(x)try{setS(JSON.parse(x))}catch{}},[])
 useEffect(()=>{localStorage.setItem("open-shelf-jh-s1",JSON.stringify(s))},[s])
 const go=(view:string,facts:string[]=[],flags:string[]=[])=>setS(x=>({...x,view,facts:add(x.facts,...facts),flags:add(x.flags,...flags)}))
 const scene=(()=>{
 if(s.view==="opening")return {k:"CHAPTER I · STORY OF THE DOOR",t:"Mr Utterson the Lawyer",p:["Mr Utterson was a man whom strangers were apt to mistake for a colder creature than he was. His countenance was rugged and seldom visited by a smile; his conversation scanty, his sentiments kept close. Yet in the acts of his life there appeared a humanity which his speech was poor at advertising.","He was austere with himself and tolerant of others. Men descending into disgrace had often found him the last reputable acquaintance who would still receive them without alteration of manner. He had a quaint doctrine for it: he let his brother go to the devil in his own way.","Among his few intimates was Mr Richard Enfield, a distant kinsman and a man of the town. The two had little in common that society could see, and nevertheless their Sunday walks were an institution: long excursions through London during which very little might be said and a great deal understood.","On one such walk they entered a busy quarter whose shops wore an air of prosperity even on the Sabbath. Near the corner, the agreeable line of the street was broken by a dingy two-storey building. Its door was blistered and discoloured; it had neither bell nor knocker. Tramps had struck matches upon it, children had played shop upon its steps, and no hand seemed ever to have driven them away.","Enfield, catching sight of the place, lifted his cane and pointed."],a:<Choice onClick={()=>go("story")}>“Did you ever remark that door?”</Choice>}
 if(s.view==="story")return {k:"A BLACK WINTER MORNING",t:"Enfield's Story",p:["Enfield had remarked it. Indeed, the door belonged to a story.","He had been coming home at about three o'clock on a black winter morning, through street after street lit by lamps and empty as a church. The solitude had worked upon him until he found himself listening for company and almost longing for the sight of a policeman.","At a corner two figures appeared: a small man walking eastward and a girl of perhaps eight or ten running hard from a cross street. They met naturally enough. Then came the part Enfield could not forget.","The man went calmly over the child's body and left her screaming on the ground.","The telling of it was almost inadequate. To hear it was one thing; Enfield's face made plain that to have seen it was another. He ran the fellow down, collared him and brought him back. The girl's family gathered; presently the doctor for whom she had been sent arrived as well.","The stranger did not struggle. He stood among them perfectly cool. Yet every person present took against him. Enfield himself felt a loathing so immediate that even recollection of the man's look seemed to trouble him.","There was no grave bodily injury, but there was outrage enough. The company told the man they would make his name stink from one end of London to the other unless he made terms. He asked what they wanted. They demanded one hundred pounds. He agreed."],a:<Choice onClick={()=>go("money",["incident","settlement"])}>Hear how the matter was settled.</Choice>}
 if(s.view==="money")return {k:"FOUR O'CLOCK",t:"The Price of Silence",p:["The stranger led them nowhere grand. He brought them to the very door before which Utterson and Enfield now stood.","From his pocket he produced a key, entered alone, and returned presently with ten pounds in gold and a cheque for the balance. The cheque was payable to bearer. The signature upon it belonged not to the little man but to another—a name Enfield would not repeat, though it was well known and often printed.","That circumstance transformed ugliness into mystery. A man did not ordinarily enter a cellar door at four in the morning and emerge carrying another gentleman's cheque for close upon a hundred pounds.","Enfield said so. The stranger merely sneered and offered to remain with them until the banks opened.","They passed what remained of the night in Enfield's chambers. After breakfast they went together to the bank. Enfield presented the cheque himself and warned that he suspected a forgery.","It was genuine.","Enfield had formed his own explanation: blackmail. Some respectable gentleman, he supposed, paying dearly for an old indiscretion. He had privately christened the building Black-Mail House."],a:<Choice onClick={()=>go("questions",["door","cheque"])}>Walk on with Enfield.</Choice>}
 if(s.view==="questions")return {k:"THE BY-STREET",t:"A Question Starts a Stone",p:["For a little while the two men regarded the door.","Utterson asked whether Enfield knew if the drawer of the cheque lived there. Enfield did not. He had noticed the gentleman's address elsewhere, but he had never asked about the place itself.","There was principle in his refusal. Questions, Enfield believed, had something of the Day of Judgment about them. Start one stone rolling downhill and presently another follows it; before long some harmless old bird is struck in his own back garden and an entire family must change its name.","The more an affair looked like Queer Street, the less Enfield asked.","Utterson approved the rule. Ordinarily, it was very nearly his own."],a:<div className="jh-choices">{!s.facts.includes("place")&&<Choice onClick={()=>go("place",["place"])}>Ask what Enfield has observed without putting questions.</Choice>}{!s.facts.includes("name")&&<Choice onClick={()=>go("name",["name"])}>Ask the name of the man who walked over the child.</Choice>}<Choice onClick={()=>go("pressSigner",[],["pressedSigner"])}>Break the rule: press Enfield for the name on the cheque.</Choice>{s.facts.includes("name")&&<Choice onClick={()=>go("appearance")}>Ask what Hyde is like to look at.</Choice>}</div>}
 if(s.view==="place")return {k:"WHAT MAY BE SEEN",t:"The House Without Questions",p:["Enfield had not questioned anybody, but he had eyes.","The place scarcely seemed a house. There was no other door. The gentleman of his adventure used this one only at intervals. Three windows looked upon the court above; none opened below. The windows were always shut, though they were clean, and a chimney generally smoked.","Somebody, therefore, appeared to live there. Yet the buildings were packed together so strangely that it was difficult to say where one ended and another began.","Enfield had learned all this by looking, which in his private code was a different sin from asking."],a:<Choice onClick={()=>go("questions")}>Continue the walk.</Choice>}
 if(s.view==="name")return {k:"ONE POINT MORE",t:"The Name",p:["Utterson walked some distance before putting the question. It was the sort of question both men had just agreed was dangerous.","Still, there was one point he wanted.","What was the name of the man who had walked over the child?","Enfield considered it and could see little harm. The man had called himself Hyde. Edward Hyde.","Utterson received the name with no outward display. But the neglected door was not wholly anonymous to him. It opened upon buildings attached to the house of Dr Henry Jekyll—his old friend, and his client. Enfield had scrupulously withheld the name upon the cheque; Utterson now understood why the story had gone home."],a:<div className="jh-choices"><Choice onClick={()=>go("appearance")}>Ask what Hyde is like to look at.</Choice><Choice onClick={()=>go("questions")}>Say nothing more for the moment.</Choice></div>}
 if(s.view==="appearance")return {k:"EDWARD HYDE",t:"A Face That Will Not Describe",p:["Enfield found the request unexpectedly difficult.","There was something wrong with Hyde's appearance, he said; something displeasing, something downright detestable. He felt certain the man must be deformed somewhere, yet could not specify the point. Hyde was extraordinary-looking, but Enfield could name nothing extraordinary about him.","It was not failure of memory. He could see the fellow at that very moment.","Utterson fell silent again. Enfield was not an imaginative man, and hatred sat awkwardly upon him. That he should remember a stranger with such force was itself worth remembering.","At length Utterson asked another question: was Enfield certain Hyde had used a key?"],a:<Choice onClick={()=>go("key",["impression"])}>Let Enfield answer.</Choice>}
 if(s.view==="key")return {k:"THE KEY",t:"Your Tale Has Gone Home",p:["The question surprised Enfield out of his usual composure.","Utterson acknowledged the strangeness of it. He knew to whose property the door belonged; that was why he had never asked Enfield for the name upon the cheque. He did not supply Jekyll's name in return. Enfield had kept another gentleman's confidence, and Utterson would keep his friend's.","Enfield was touched with sullenness. Utterson might have warned him. But on the point of the key he had been exact—pedantically exact. Hyde had possessed one that night, and possessed it still. Enfield had seen him use it less than a week ago.","Utterson sighed and said nothing.","Enfield drew the lesson differently. His long tongue had already carried them farther than either gentleman liked."],a:<div className="jh-choices"><Choice onClick={()=>go("bargain",["key"])}>Agree never to refer to the matter again.</Choice><Choice onClick={()=>go("refuseBargain",["key"],["noBargain"])}>Refuse to promise silence where a friend may be concerned.</Choice></div>}
 if(s.view==="pressSigner")return {k:"A QUESTION TOO FAR",t:"The Name Enfield Will Not Give",p:["Utterson did not let the matter rest. He asked whose name had stood upon the cheque.","Enfield's expression altered. The refusal, when it came, was civil but absolute. He had told the story because the door had recalled it; he had not told it to spread another man's private affairs through London.","The cheque was genuine. The name was respectable. That was as far as Enfield would go.","For a few paces their Sunday silence was no longer companionable but defensive. Utterson had obtained no name, only the knowledge that his kinsman's rule against questions had a boundary he would enforce."],a:<div className="jh-choices"><Choice onClick={()=>go("questions")}>Respect the refusal and return to what Enfield will tell you.</Choice><Choice onClick={()=>go("endStrain",[],["strainedEnfield"])}>Press him once more.</Choice></div>}
 if(s.view==="bargain")return {k:"SLICE I · CANONICAL FRONTIER",t:"A Bargain of Silence",p:["Enfield proposed that they should never refer to the story again.","Utterson accepted with all his heart. The two kinsmen shook hands upon it and continued their Sunday walk.","The promise was between the two men: neither would make Enfield's story a subject of conversation. It did not oblige Utterson to forget what he knew, nor to neglect the private duties of a solicitor and friend.","He carried away a name, a key, a door and the knowledge that Henry Jekyll's affairs touched all three. Indeed, the agreement against gossip made private inquiry the more natural course left open to him.","The Sunday walk ended. The matter did not. Chapter II will begin with Utterson still bound by his promise to Enfield, and still free to act upon his concern."],a:<Choice onClick={()=>setS(start)}>Begin Slice I again.</Choice>}
 if(s.view==="refuseBargain")return {k:"SLICE I · DIVERGENT FRONTIER",t:"No Promise Given",p:["Utterson did not take Enfield's offered bargain.","He would not make gossip of the story, he said; but neither would he promise never to speak of it. There were circumstances in which silence might cease to be kindness.","Enfield looked at him closely. Utterson was not a man given to dramatic declarations, which made this one more noticeable.","The walk resumed, but the matter had not been sealed away between them. Enfield now knew that the story had touched something personal in his kinsman, though Utterson had not told him what.","That small refusal altered what might follow. Enfield remained a man Utterson could speak to again; and Utterson entered the coming days under no promise that forbade him from doing so."],a:<Choice onClick={()=>setS(start)}>Begin Slice I again.</Choice>}
 if(s.view==="endStrain")return {k:"SLICE I · DIVERGENT FRONTIER",t:"The Cost of Asking",p:["Utterson asked again.","Enfield stopped walking. He would not give the name, and this time there was no softness in the refusal. A confidence had not been offered merely to become an examination.","Utterson let the matter drop, but too late to pretend he had never pressed it. Their walk continued. The old habit of silence returned, though for the remainder of that Sunday it had acquired an edge.","Nothing about the mystery had been solved. What Utterson had changed was the instrument by which he might later pursue it: Enfield would be less willing to be questioned, and perhaps less willing to volunteer what he saw.","That was not an end to the inquiry. It was a poorer beginning to whatever came next."],a:<Choice onClick={()=>setS(start)}>Begin Slice I again.</Choice>}
 return {k:"STORY OF THE DOOR",t:"The Walk Continues",p:["London receives them again."],a:<Choice onClick={()=>go("questions")}>Continue.</Choice>}
 })()
 return <main className="jh-page"><header className="jh-head"><Link href="/">← THE OPEN SHELF</Link><div><span>ROBERT LOUIS STEVENSON · 1886</span><h1>Dr Jekyll <i>&</i> Mr Hyde</h1><p>SLICE I · STORY OF THE DOOR</p></div><button onClick={()=>setS(start)}>NEW CASE</button></header><section className="jh-case"><aside className="jh-docket"><h2>CASE PAPERS</h2><p className="muted">Utterson records what he has actually learned. The story is where he learns it.</p>{s.facts.length===0?<p className="muted">Nothing yet entered.</p>:s.facts.map(id=><button className="paper-slip" key={id} onClick={()=>setPaper(id)}><small>{F[id]?.source}</small><strong>{F[id]?.title}</strong></button>)}<h2>THE WALK</h2><p>{s.flags.includes("pressedSigner")?"You pressed Enfield beyond his rule of discretion.":"Enfield's confidence is intact."}</p></aside><article className="jh-story"><div className="jh-kicker">{scene.k}</div><h2>{scene.t}</h2>{scene.p.map((p,i)=><p key={i}>{p}</p>)}<div className="jh-choices">{scene.a}</div><footer>Slice I ends with Chapter I. Choices alter circumstances; they do not select an ending.</footer></article></section>{paper&&F[paper]&&<div className="paper-modal" onClick={()=>setPaper(null)}><div className="paper" onClick={e=>e.stopPropagation()}><button onClick={()=>setPaper(null)}>CLOSE ×</button><small>{F[paper].source}</small><h3>{F[paper].title}</h3><p>{F[paper].text}</p></div></div>}</main>
}