"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"

type Stats={resolve:number;discretion:number;suspicion:number;hour:number}
type Game={scene:string;stats:Stats;clues:string[];journal:string[];flags:Record<string,boolean>}
type Choice={label:string;to:string;note:string;effect?:(g:Game)=>Game}
type Scene={chapter:string;place:string;title:string;text:string[];choices:Choice[]}

const start:Game={scene:"walk",stats:{resolve:2,discretion:3,suspicion:0,hour:16},clues:[],flags:{},journal:["Sunday. Enfield and I took our customary walk. London seemed determined to keep its secrets."]}
const addClue=(name:string)=>(g:Game):Game=>g.clues.includes(name)?g:{...g,clues:[...g.clues,name]}
const mark=(flag:string)=>(g:Game):Game=>({...g,flags:{...g.flags,[flag]:true}})
const stat=(key:keyof Stats,n:number)=>(g:Game):Game=>({...g,stats:{...g.stats,[key]:Math.max(0,g.stats[key]+n)}})
const pipe=(...fns:Array<(g:Game)=>Game>)=>(g:Game)=>fns.reduce((v,f)=>f(v),g)

const scenes:Record<string,Scene>={
walk:{chapter:"I",place:"A BY-STREET IN LONDON",title:"Story of the Door",text:["Your Sunday walk with Richard Enfield has carried you into a prosperous street, bright with trade even under London's tired afternoon.","One feature spoils it: a blistered door in a neglected building. Enfield slows. He knows the place.","“Did you ever remark that door?” he asks. There is something in his voice which makes the question heavier than it ought to be."],choices:[{label:"Ask what happened at the door",to:"enfield",note:"Some stories are offered because they want telling."},{label:"Study the building before answering",to:"door",note:"A lawyer learns to notice what other men edit out.",effect:stat("resolve",1)}]},
door:{chapter:"I",place:"THE DOOR",title:"A House Without Windows",text:["The door has neither bell nor knocker. The upper storey shows windows, but no sign of habitation. The neglect is conspicuous precisely because the street around it is not.","Enfield watches you inspect it. “Yes,” he says. “That is the place.”"],choices:[{label:"Hear Enfield's story",to:"enfield",note:"The door has acquired a witness.",effect:addClue("The neglected door")}]},
enfield:{chapter:"I",place:"THE BY-STREET",title:"The Man Who Trampled Calmly",text:["Enfield tells you of a winter morning at three: a little girl running through a crossing, and a small man colliding with her.","The man did not merely knock her down. He walked over her body and continued on with perfect composure.","A crowd detained him. The sight of him produced an immediate, inexplicable loathing. To avoid scandal he paid one hundred pounds—ten in gold, the remainder by cheque. The cheque bore the name of a man whose reputation you know very well."],choices:[{label:"Ask the man's name",to:"name",note:"Names turn anecdotes into cases."},{label:"Ask whose cheque it was",to:"silence",note:"Enfield has already decided that question should not be answered.",effect:stat("discretion",-1)}]},
silence:{chapter:"I",place:"THE BY-STREET",title:"The Rule of Silence",text:["Enfield's expression closes. He will not name the drawer of the cheque. He calls the business blackmail, though he admits he has no proof.","You understand his instinct. Respectable London survives because gentlemen know when not to ask.","Unfortunately, you are a solicitor."],choices:[{label:"Ask instead for the stranger's name",to:"name",note:"A narrower question may travel further.",effect:stat("suspicion",1)}]},
name:{chapter:"I",place:"THE BY-STREET",title:"Edward Hyde",text:["“His name was Hyde,” says Enfield. “Edward Hyde.”","The name lands badly. You cannot say why.","Enfield cannot describe him cleanly. Deformed, perhaps—but no deformity he can name. Something displeasing. Something detestable.","Then the neglected door ceases to be merely a door. You know whose house lies connected to it."],choices:[{label:"Say nothing. Go home and open the safe.",to:"will",note:"Henry Jekyll's will has troubled you for months.",effect:pipe(addClue("Edward Hyde"),mark("heardHyde"),stat("hour",3))}]},
will:{chapter:"II",place:"UTTERSON'S HOUSE",title:"The Will",text:["Dinner passes without appetite. You dismiss the servants, light a candle, and unlock your private safe.","The document is exactly as you remember it. In the event of Dr Henry Jekyll's death, all possessions pass to his friend and benefactor Edward Hyde. Worse: should Jekyll disappear for more than three calendar months, Hyde assumes Jekyll's place without delay.","You drafted none of this. You objected to all of it."],choices:[{label:"Go to Dr Lanyon tonight",to:"lanyon",note:"An old friend may know what Jekyll refuses to tell you.",effect:addClue("Jekyll's extraordinary will")},{label:"Begin watching the door yourself",to:"watch",note:"If Hyde uses that entrance, patience will produce him.",effect:pipe(addClue("Jekyll's extraordinary will"),stat("resolve",1))}]},
lanyon:{chapter:"II",place:"CAVENDISH SQUARE",title:"Dr Lanyon",text:["Dr Hastie Lanyon receives you warmly among the dark wood and good wine of his dining room.","At Jekyll's name his warmth cools. Ten years ago, he says, Henry became too fanciful for him—wrong in mind, wrong in his unscientific balderdash.","But Edward Hyde? Lanyon has never heard the name."],choices:[{label:"Press Lanyon about Jekyll's experiments",to:"lanyonPress",note:"Professional contempt sometimes conceals useful detail.",effect:stat("discretion",-1)},{label:"Leave the quarrel alone and watch the door",to:"watch",note:"There is no evidence here—only an old wound.",effect:addClue("Jekyll and Lanyon's estrangement")}]},
lanyonPress:{chapter:"II",place:"CAVENDISH SQUARE",title:"The Old Quarrel",text:["Lanyon bristles. Jekyll, he says, abandoned the solid ground of medicine for transcendental nonsense.","Yet one phrase stays with you: Jekyll had begun claiming that man's identity was less singular than respectable science supposed.","Lanyon immediately regrets saying even that much."],choices:[{label:"Apologise and begin the watch",to:"watch",note:"You have learned enough to be uneasy.",effect:pipe(addClue("Jekyll's divided-self theory"),stat("suspicion",1))}]},
watch:{chapter:"II",place:"THE DOOR",title:"Mr Hyde",text:["Days pass. You alter your routes, your meals, your sleep. Morning, noon and night you haunt the by-street until persistence is rewarded.","Footsteps approach. A small man comes quickly toward the door. Before he can insert his key, you step forward.","“Mr Hyde?”","He recoils, then masters himself. Up close, Enfield's failure makes sense. There is something wrong in the man that refuses to become a feature you can name."],choices:[{label:"Tell him you are an old friend of Dr Jekyll",to:"hydeTalk",note:"Courtesy first. It is still London.",effect:mark("metHyde")},{label:"Block the door and ask how he knows Jekyll",to:"hydeHard",note:"You are done being polite.",effect:pipe(mark("metHyde"),stat("resolve",1),stat("suspicion",1))}]},
hydeTalk:{chapter:"II",place:"THE DOOR",title:"A Civil Exchange",text:["Hyde gives you an address in Soho when you ask where he may be found. He even permits you a clear look at his face.","Then he smiles. It is not a pleasant success.","“How did you know me?” he asks.","You answer that you have common friends. Jekyll, for instance.","“He never told you,” Hyde says, and slips through the door."],choices:[{label:"Go directly to Jekyll's house",to:"poole",note:"The key matters more than Hyde's manners.",effect:addClue("Hyde's Soho address")},{label:"Follow Hyde through Soho",to:"follow",note:"A solicitor can occasionally behave like a detective.",effect:pipe(addClue("Hyde's Soho address"),stat("discretion",-1))}]},
hydeHard:{chapter:"II",place:"THE DOOR",title:"An Unwise Question",text:["Hyde's expression changes so quickly you almost miss it. For one instant the civility falls away.","“You should mind your profession, Mr Utterson.”","He knows your name. You did not give it.","Then he is behind the door, and the key turns."],choices:[{label:"Go to Jekyll's front entrance",to:"poole",note:"Someone has been discussing you.",effect:addClue("Hyde knew Utterson's name")}]},
follow:{chapter:"II",place:"SOHO",title:"At a Distance",text:["You follow badly. Hyde knows these streets and you do not. Twice you nearly lose him in the fog.","At last he enters a house in a dingy quarter of Soho. You mark the address—the same one he gave you—and the woman at the window who watches him enter.","You have gained little, except certainty that Hyde expected to be found here."],choices:[{label:"Return to Jekyll's house",to:"poole",note:"Time to ask about the key.",effect:addClue("Hyde's Soho rooms observed")}]},
poole:{chapter:"II",place:"DR JEKYLL'S HOUSE",title:"The Key",text:["Poole admits you at Jekyll's respectable front entrance. The doctor is out.","You ask whether Hyde is permitted to enter by the laboratory door.","“O dear no, sir. Mr Hyde has a key.”","All the servants have orders to obey him.","The shape of the danger changes. Hyde is not merely extorting Jekyll from outside. Jekyll has installed him inside."],choices:[{label:"Go home and prepare for the worst",to:"chapter3",note:"If Hyde is waiting to inherit, you will wait longer.",effect:addClue("Hyde possesses Jekyll's key")},{label:"Ask Poole to tell you whenever Hyde appears",to:"pooleAlliance",note:"A servant sees what a gentleman's friends do not.",effect:stat("discretion",-1)}]},
pooleAlliance:{chapter:"II",place:"DR JEKYLL'S HOUSE",title:"A Quiet Arrangement",text:["Poole hesitates. Loyalty to his master wars visibly with fear.","You do not ask him to spy. You ask him to send word if Jekyll appears endangered.","That distinction is thin enough for both of you to accept."],choices:[{label:"Leave before Jekyll returns",to:"chapter3",note:"You have acquired an ally, though neither of you calls it that.",effect:pipe(mark("pooleAlly"),addClue("Poole's quiet assistance"),stat("suspicion",1))}]},
chapter3:{chapter:"III",place:"DR JEKYLL'S DINING ROOM",title:"Quite at Ease",text:["Two weeks later Jekyll gives one of his pleasant dinners. When the last guest leaves, you remain.","Henry looks well: a large, handsome man of fifty, perhaps a little sly about the mouth, but every inch the old friend you remember.","You mention the will.","The warmth goes out of the room."],choices:[{label:"Tell Jekyll plainly that you have met Hyde",to:"jekyllTruth",note:"Friendship occasionally requires bad manners.",effect:stat("resolve",1)},{label:"Pretend concern only about the will",to:"jekyllSoft",note:"Give Jekyll room to choose honesty.",effect:stat("discretion",1)}]},
jekyllTruth:{chapter:"III",place:"DR JEKYLL'S DINING ROOM",title:"A Promise",text:["Jekyll grows pale. He insists the matter is private and that he can be rid of Hyde whenever he chooses.","You do not believe the first claim. The second frightens you more.","At last he asks one thing: if he is taken away, see that Hyde receives his rights.","You promise only that you will ensure justice—not obedience."],choices:[{label:"Continue",to:"interlude",note:"The case is no longer professional. It is personal.",effect:pipe(mark("challengedJekyll"),addClue("Jekyll claims control over Hyde"))}]},
jekyllSoft:{chapter:"III",place:"DR JEKYLL'S DINING ROOM",title:"The Gentleman's Answer",text:["Jekyll smiles too quickly. He says you do not understand his position and cannot understand it.","He can be rid of Hyde whenever he chooses. There is no danger.","Then he asks you to promise that, should anything happen, you will help Hyde.","You give the promise reluctantly. Jekyll looks relieved. You do not."],choices:[{label:"Continue",to:"interlude",note:"You have preserved Jekyll's confidence—for now.",effect:pipe(mark("keptConfidence"),addClue("Jekyll claims control over Hyde"))}]},
interlude:{chapter:"IV",place:"LONDON",title:"Nearly a Year Later",text:["For months, nothing happens.","Hyde vanishes from your sight. Jekyll appears sociable. You almost persuade yourself that whatever sickness touched your friend's life has passed.","Then, one October night, a maid looking from an upper window sees an elderly gentleman address a small man in the street.","She recognises the smaller man.","Edward Hyde raises his cane."],choices:[{label:"Answer the police summons",to:"carew",note:"The quiet part of the case is over.",effect:stat("hour",8)}]},
carew:{chapter:"IV",place:"A POLICE MORTUARY",title:"The Carew Murder Case",text:["The victim is Sir Danvers Carew. In his pocket is a letter addressed to you.","The body is terribly broken. Beside it lies half of a heavy cane.","You recognise the cane. Years ago, you gave it to Henry Jekyll."],choices:[{label:"Take Inspector Newcomen to Hyde's Soho rooms",to:"sohoRaid",note:"You know exactly where to go.",effect:addClue("Jekyll's cane at Carew's murder")},{label:"Go to Jekyll before revealing Hyde's address",to:"warnJekyll",note:"Friendship and justice have finally become opponents.",effect:pipe(addClue("Jekyll's cane at Carew's murder"),stat("suspicion",2))}]},
warnJekyll:{chapter:"IV",place:"DR JEKYLL'S HOUSE",title:"Before the Police",text:["Poole's face tells you Jekyll is home. You have perhaps an hour before Newcomen learns what you already know.","This is the first moment in which your choices have carried you materially away from the course events once seemed determined to take.","Behind the laboratory door, something moves."],choices:[{label:"Knock and confront Jekyll",to:"endingIntervene",note:"You will not wait politely for another corpse.",effect:stat("resolve",2)},{label:"Turn back. Take the police to Soho.",to:"sohoRaid",note:"The law must have its turn.",effect:stat("discretion",1)}]},
sohoRaid:{chapter:"IV",place:"SOHO",title:"Hyde's Rooms",text:["Newcomen is delighted by your information. Hyde's rooms are furnished in luxury and violence: good pictures, fine wine, clothes scattered, drawers ransacked.","The other half of the cane lies behind a door.","Hyde himself is gone.","On the hearth, papers have been burned. One corner remains legible enough to bear Jekyll's hand."],choices:[{label:"Pocket the fragment before Newcomen sees it",to:"endingSecret",note:"A terrible breach of duty—for a friend.",effect:pipe(addClue("Burned fragment in Jekyll's hand"),stat("discretion",-2),stat("suspicion",2))},{label:"Give the fragment to Newcomen",to:"endingLaw",note:"Whatever Jekyll has done, concealment ends here.",effect:pipe(addClue("Burned fragment in Jekyll's hand"),stat("resolve",1))}]},
endingIntervene:{chapter:"—",place:"THE LABORATORY DOOR",title:"ENDING I — The Knock Before Midnight",text:["You knock until courtesy becomes accusation.","Jekyll answers at last. His voice is wrong.","What follows is not the end of the strange case. It is the moment its familiar course breaks.","You have arrived too early for Henry Jekyll's carefully arranged tragedy. He must now decide whether to trust Gabriel Utterson with an impossible truth—or become the monster he has been hiding while his oldest friend stands on the other side of the door.","This path will continue in the full game."],choices:[]},
endingSecret:{chapter:"—",place:"SOHO",title:"ENDING II — Counsel for the Damned",text:["The scrap disappears into your coat.","Newcomen finds enough evidence to hunt Hyde, but not enough to connect every thread to Henry Jekyll.","You have crossed a line you have spent your career defending.","Perhaps it will save your friend. Perhaps it will merely give his secret more time to grow teeth.","This path will continue in the full game."],choices:[]},
endingLaw:{chapter:"—",place:"SOHO",title:"ENDING III — Fiat Justitia",text:["You hand the fragment to Inspector Newcomen.","For the first time, the law can see the shape you have been circling.","Jekyll's name will not remain outside the investigation. Whatever friendship demands of you now, secrecy is no longer available.","London loves a respectable man almost as much as it loves destroying one.","This path will continue in the full game."],choices:[]}
}

function applyChoice(game:Game,c:Choice){let next={...game,scene:c.to,stats:{...game.stats,hour:game.stats.hour+1},journal:[...game.journal,c.note]};if(c.effect)next=c.effect(next);return next}
export default function JekyllHyde(){
 const [game,setGame]=useState<Game>(start);const [loaded,setLoaded]=useState(false)
 useEffect(()=>{try{const s=localStorage.getItem("open-shelf-jh");if(s)setGame(JSON.parse(s))}catch{}setLoaded(true)},[])
 useEffect(()=>{if(loaded)localStorage.setItem("open-shelf-jh",JSON.stringify(game))},[game,loaded])
 const scene=scenes[game.scene]||scenes.walk
 const time=useMemo(()=>String(game.stats.hour%24).padStart(2,"0")+":00",[game.stats.hour])
 const reset=()=>{localStorage.removeItem("open-shelf-jh");setGame(start)}
 return <main className="jh"><header className="jh-top"><Link href="/" className="jh-back">← THE OPEN SHELF</Link><span>ROBERT LOUIS STEVENSON · 1886</span></header>
 <section className="jh-title"><p>THE STRANGE CASE OF</p><h1>Dr Jekyll <i>&</i><br/><b>Mr Hyde</b></h1><div className="jh-role">YOU ARE<br/><strong>G. J. UTTERSON</strong><br/><small>Solicitor · Friend · Witness</small></div></section>
 <section className="jh-case"><aside className="jh-docket"><div><small>CHAPTER</small><strong>{scene.chapter}</strong></div><div><small>PLACE</small><strong>{scene.place}</strong></div><div><small>HOUR</small><strong>{time}</strong></div><hr/><div className="meters"><small>YOUR TEMPERAMENT</small><label>Resolve <span>{"●".repeat(Math.min(game.stats.resolve,5))}{"○".repeat(Math.max(0,5-game.stats.resolve))}</span></label><label>Discretion <span>{"●".repeat(Math.min(game.stats.discretion,5))}{"○".repeat(Math.max(0,5-game.stats.discretion))}</span></label><label>Suspicion <span>{"●".repeat(Math.min(game.stats.suspicion,5))}{"○".repeat(Math.max(0,5-game.stats.suspicion))}</span></label></div><hr/><div className="clues"><small>CASE PAPERS · {game.clues.length}</small>{game.clues.length?game.clues.map(x=><p key={x}>— {x}</p>):<p className="muted">Nothing entered.</p>}</div></aside>
 <article className="jh-page"><p className="folio">{scene.place}</p><h2>{scene.title}</h2><div className="jh-prose">{scene.text.map((p,i)=><p key={i}>{p}</p>)}</div>{scene.choices.length>0?<div className="jh-choices"><p>WHAT WILL YOU DO?</p>{scene.choices.map((c,i)=><button key={c.label} onClick={()=>setGame(g=>applyChoice(g,c))}><span>{String(i+1).padStart(2,"0")}</span><b>{c.label}</b><em>{c.note}</em></button>)}</div>:<div className="jh-ending"><button onClick={reset}>BEGIN THE CASE AGAIN</button><Link href="/">RETURN TO THE OPEN SHELF</Link></div>}</article></section>
 <details className="jh-journal"><summary>UTTERSON'S PRIVATE NOTES · {game.journal.length}</summary>{game.journal.map((x,i)=><p key={i}><span>{String(i+1).padStart(2,"0")}</span>{x}</p>)}</details><footer className="jh-foot"><span>Progress is saved in this browser.</span><button onClick={reset}>RESET CASE</button></footer></main>
}
